tags:
- name: test
  description: test

paths:
  /user:
    get:
      tags:
      - test
      summary: test
      responses:
        200:
          description: 'Success'
        500:
          description: 'Server Error'
# definitions
definitions:
  user:
    type: object
    properties:
      test:
        type: "string"
        description: "test"
schemes:
 - https
 - http